version: '1'
services:
  web:
    build:
      context: .
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    depends_on:
      - postgres

  postgres:
    image: mayok/postgresql-summpy
    command: "psqld"
    volumes:
      - "postgres-webapp-data:/var/lib/postgresd"
    environments:
      - "POSTGRESQL_PASSWORD=password"


volumes:
  postgres-webapp-data:
