version: '3'
services:
  postgres:
    image: mayok/postgresql

  web:
    build:
      context: .
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    links:
      - postgres
    environment:
      - PGHOST=db
      - PGUSER=summpy
      - PGDATABASE=summpy

