version: '3'
services:
  postgres:
    image: mayok/postgres
    # build:
    #   context: ./postgres
    # environment:
    #   - POSTGRES_PASSWORD=password

  backend:
    build:
      context: ./backend
    volumes:
      - .:/home/app/backend
      - /home/app/backend/node_modules
    ports:
      - "3000:3000"
    links:
      - postgres
    environment:
      - PGHOST=postgres
      - PGUSER=summpy
      - PGPASSWORD=password
      - PGDATABASE=summpy

  # fronend:
  #   build:
  #     context: ./fronend
  #   volumes:
  #     .:/home/app/frontend
  #     /home/app/frontend/node_modules
  #   ports:
  #     - "3000:3000"
